/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SignInIndexImport } from './routes/signIn/index'

// Create Virtual Routes

const MyBooksLazyImport = createFileRoute('/myBooks')()

// Create/Update Routes

const MyBooksLazyRoute = MyBooksLazyImport.update({
  id: '/myBooks',
  path: '/myBooks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/myBooks.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SignInIndexRoute = SignInIndexImport.update({
  id: '/signIn/',
  path: '/signIn/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/myBooks': {
      id: '/myBooks'
      path: '/myBooks'
      fullPath: '/myBooks'
      preLoaderRoute: typeof MyBooksLazyImport
      parentRoute: typeof rootRoute
    }
    '/signIn/': {
      id: '/signIn/'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/myBooks': typeof MyBooksLazyRoute
  '/signIn': typeof SignInIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/myBooks': typeof MyBooksLazyRoute
  '/signIn': typeof SignInIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/myBooks': typeof MyBooksLazyRoute
  '/signIn/': typeof SignInIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/myBooks' | '/signIn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/myBooks' | '/signIn'
  id: '__root__' | '/' | '/myBooks' | '/signIn/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyBooksLazyRoute: typeof MyBooksLazyRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyBooksLazyRoute: MyBooksLazyRoute,
  SignInIndexRoute: SignInIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/myBooks",
        "/signIn/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/myBooks": {
      "filePath": "myBooks.lazy.tsx"
    },
    "/signIn/": {
      "filePath": "signIn/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
